name: Scala CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install sbt (via Coursier)
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Compile
        run: sbt compile

      - name: Run tests
        run: sbt test

  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install sbt (via Coursier)
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Run coverage and upload to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          sbt clean coverage test coverageReport coveralls

  count_lines:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install cloc
        run: sudo apt-get install -y cloc

      - name: Run cloc and export JSON
        run: cloc --json --exclude-dir=.git,test,target . > cloc.json

      - name: Upload cloc.json
        uses: actions/upload-artifact@v3
        with:
          name: cloc-json
          path: cloc.json
