name: Scala CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  test-and-cover:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install sbt (via Coursier)
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Run tests and upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          sbt clean coverage test coverageReport coverageAggregate coveralls
