name: Scala CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install sbt (via Coursier)
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Compile
        run: sbt compile

      - name: Run tests
        run: sbt test

  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install sbt (via Coursier)
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Run coverage and upload to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          sbt clean coverage test coverageReport coveralls

  count_lines:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install cloc
        run: sudo apt-get install -y cloc

      - name: Generate cloc.json
        run: |
          mkdir -p .github/workflows
          cloc --json --exclude-dir=.git,test,target . > .github/workflows/cloc.json

      - name: Commit cloc.json to a branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -b badges || git checkout badges
          git add .github/stats/cloc.json
          git commit -m "Update cloc stats" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:badges
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


